package com.star_zero.compose.previewcollector

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent

class PreviewCollectionActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            // Generated by ksp
            com.star_zero.compose.previewcolletctor.PreviewCollection()
        }
    }
}